//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanMyPham.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOUCHER()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MaVoucher { get; set; }
        public string Code { get; set; }
        [Range(0, double.MaxValue, ErrorMessage = "Giá trị giảm giá phải lớn hơn hoặc bằng 0")]
        public decimal GiamGia { get; set; }
        public bool LoaiGiamGia { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng voucher phải lớn hơn hoặc bằng 0")]
        public int SoLuong { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayHetHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
    }
}
